// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PingMessage_Method int32

const (
	PingMessage_ADD    PingMessage_Method = 0
	PingMessage_DELETE PingMessage_Method = 1
	PingMessage_PATCH  PingMessage_Method = 2
)

var PingMessage_Method_name = map[int32]string{
	0: "ADD",
	1: "DELETE",
	2: "PATCH",
}

var PingMessage_Method_value = map[string]int32{
	"ADD":    0,
	"DELETE": 1,
	"PATCH":  2,
}

func (x PingMessage_Method) String() string {
	return proto.EnumName(PingMessage_Method_name, int32(x))
}

func (PingMessage_Method) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0, 0}
}

type PingMessage struct {
	UniqId               string                 `protobuf:"bytes,1,opt,name=uniq_id,json=uniqId,proto3" json:"uniq_id,omitempty"`
	SeriTime             *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=seri_time,json=seriTime,proto3" json:"seri_time,omitempty"`
	Method               PingMessage_Method     `protobuf:"varint,3,opt,name=method,proto3,enum=PingMessage_Method" json:"method,omitempty"`
	Data                 string                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *PingMessage) Reset()         { *m = PingMessage{} }
func (m *PingMessage) String() string { return proto.CompactTextString(m) }
func (*PingMessage) ProtoMessage()    {}
func (*PingMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *PingMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingMessage.Unmarshal(m, b)
}
func (m *PingMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingMessage.Marshal(b, m, deterministic)
}
func (m *PingMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingMessage.Merge(m, src)
}
func (m *PingMessage) XXX_Size() int {
	return xxx_messageInfo_PingMessage.Size(m)
}
func (m *PingMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_PingMessage.DiscardUnknown(m)
}

var xxx_messageInfo_PingMessage proto.InternalMessageInfo

func (m *PingMessage) GetUniqId() string {
	if m != nil {
		return m.UniqId
	}
	return ""
}

func (m *PingMessage) GetSeriTime() *timestamppb.Timestamp {
	if m != nil {
		return m.SeriTime
	}
	return nil
}

func (m *PingMessage) GetMethod() PingMessage_Method {
	if m != nil {
		return m.Method
	}
	return PingMessage_ADD
}

func (m *PingMessage) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterEnum("PingMessage_Method", PingMessage_Method_name, PingMessage_Method_value)
	proto.RegisterType((*PingMessage)(nil), "PingMessage")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 220 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x97, 0x92, 0x4f, 0xcf, 0xcf, 0x4f, 0xcf,
	0x49, 0xd5, 0x07, 0xf3, 0x92, 0x4a, 0xd3, 0xf4, 0x4b, 0x32, 0x73, 0x53, 0x8b, 0x4b, 0x12, 0x73,
	0x0b, 0x20, 0x0a, 0x94, 0x4e, 0x31, 0x72, 0x71, 0x07, 0x64, 0xe6, 0xa5, 0xfb, 0x42, 0xb4, 0x09,
	0x89, 0x73, 0xb1, 0x97, 0xe6, 0x65, 0x16, 0xc6, 0x67, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70,
	0x06, 0xb1, 0x81, 0xb8, 0x9e, 0x29, 0x42, 0xe6, 0x5c, 0x9c, 0xc5, 0xa9, 0x45, 0x99, 0xf1, 0x20,
	0x03, 0x24, 0x98, 0x14, 0x18, 0x35, 0xb8, 0x8d, 0xa4, 0xf4, 0x20, 0xa6, 0xeb, 0xc1, 0x4c, 0xd7,
	0x0b, 0x81, 0x99, 0x1e, 0xc4, 0x01, 0x52, 0x0c, 0xe2, 0x0a, 0x69, 0x73, 0xb1, 0xe5, 0xa6, 0x96,
	0x64, 0xe4, 0xa7, 0x48, 0x30, 0x2b, 0x30, 0x6a, 0xf0, 0x19, 0x09, 0xeb, 0x21, 0xd9, 0xa7, 0xe7,
	0x0b, 0x96, 0x0a, 0x82, 0x2a, 0x11, 0x12, 0xe2, 0x62, 0x49, 0x49, 0x2c, 0x49, 0x94, 0x60, 0x01,
	0xdb, 0x0d, 0x66, 0x2b, 0x69, 0x70, 0xb1, 0x41, 0x54, 0x09, 0xb1, 0x73, 0x31, 0x3b, 0xba, 0xb8,
	0x08, 0x30, 0x08, 0x71, 0x71, 0xb1, 0xb9, 0xb8, 0xfa, 0xb8, 0x86, 0xb8, 0x0a, 0x30, 0x0a, 0x71,
	0x72, 0xb1, 0x06, 0x38, 0x86, 0x38, 0x7b, 0x08, 0x30, 0x25, 0xb1, 0x81, 0x1d, 0x62, 0x0c, 0x08,
	0x00, 0x00, 0xff, 0xff, 0xc6, 0x0e, 0x34, 0x8a, 0x05, 0x01, 0x00, 0x00,
}
