// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"pinggo/internal/svc"

	"gitlab.deepwisdomai.com/infra/go-zero/rest"
)

func RegisterHandlers(engine *rest.Server, serverCtx *svc.ServiceContext) {
	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/health",
				Handler: HealthCheckHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/metrics",
				Handler: MetricsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/ping",
				Handler: DataBatchUploadHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/api/ping",
				Handler: DatBatchDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/data/record",
				Handler: DataRecordHandler(serverCtx),
			},
		},
	)
}
