// Code generated by goctl. DO NOT EDIT.
package types

type CommonResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data"`
}

type TrainDataBatchRequest struct {
	Appkey string                   `json:"appkey"`
	AtId   string                   `json:"at_id"`
	Data   []map[string]interface{} `json:"data"`
}

type DataUploadRecord struct {
	Appkey string `json:"appkey"`
}

type DataUploadRecords struct {
	Data   []DataUploadRecord `json:"data"`
	Appkey string             `json:"appkey"`
}

type DataUploadRequest struct {
	Appkey string `json:"appkey"`
	Start  string `json:"start"`
	End    string `json:"end"`
	Page   int    `json:"page"`
	Size   int    `json:"size"`
}
